---
swagger: "2.0"
info:
  version: 1.0.0
  description: A REST interface for irisnet state queries.
  title: explorer for the irisnet

consumes:
  - application/json
produces:
  - application/json

schemes:
  - http

tags:
  - name: BlockInfo
    description: Block APIs, such as query coin flow,proposal,validatorset
  - name: Block
    description: query blocks
  - name: Governance/Proposal
    description: query proposal
  - name: stake
    description:
paths:
  /api/block/{height}:
    get:
      summary: Get a block information at a certain height
      tags:
        - BlockInfo
      parameters:
        - in: path
          name: height
          description: Block height
          required: true
          type: integer
          format: int64
          default: 1
      responses:
        200:
          description: The block info at a specific height
          schema:
            $ref: "#/definitions/Block"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/stake/validatorset:
    get:
      tags:
        - BlockInfo
      parameters:
        - name: height
          in: query
          description: Block height
          type: integer
          format: int64
          default: 1
        - name: page
          in: query
          type: integer
          format: int
          default: 1
          required: false
        - name: size
          in: query
          type: integer
          format: int
          default: 10
          required: false
      responses:
        200:
          description: get a validatorset by block height
          schema:
            $ref: "#/definitions/ValidatorSet"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/tx/token/flow:
    get:
      tags:
        - BlockInfo
      parameters:
        - name: height
          in: query
          description: Block height
          type: integer
          format: int64
          default: 1
        - name: page
          in: query
          type: integer
          format: int
          default: 1
          required: false
        - name: size
          in: query
          type: integer
          format: int
          default: 10
          required: false
      responses:
        200:
          description: list the token flow
          schema:
            $ref: "#/definitions/TokenFlows"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/blocks:
    get:
      tags:
        - Block
      parameters:
        - name: page
          in: query
          type: integer
          format: int
          default: 1

          required: false
        - name: size
          in: query
          type: integer
          format: int
          default: 100

          required: false
      responses:
        200:
          description: query recent blocks
          schema:
            $ref: "#/definitions/Blocks"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/blocks/recent:
    get:
      summary: query the recent blocks
      tags:
        - Block
      responses:
        200:
          description: 
          schema:
          type: array
          items:
            $ref: "#/definitions/BlockInfoVo"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/proposal/{pid}:
    get:
      summary: query a proposal
      tags:
        - Governance/Proposal
      parameters:
        - in: path
          name: pid
          description: query a proposal by id
          required: true
          type: integer
          format: int
      responses:
        200:
          description:
          schema:
            $ref: "#/definitions/ProposalInfoVo"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/proposals/{page}/{size}:
    get:
      tags:
        - Governance/Proposal
      parameters:
        - in: path
          name: page
          type: integer
          format: int
          default: 1
        - in: path
          name: size
          type: integer
          format: int
          default: 20
      responses:
        200:
          schema:
            $ref: "#/definitions/GovProposals"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /api/stake/validators:
    get:
      tags:
      - stake
      parameters:
        - name: page
          in: query
          type: integer
          format: int64
          default: 1
        - name: size
          in: query
          type: integer
          format: int64
          default: 100
        - name: type
          in: query
          type: string
        - name: origin
          in: query
          type: string
      responses:
        200:
          description:
          schemas:
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  Blocks:
    type: object
    required:
      - Count
      - Data
    properties:
      Count:
        type: integer
        format: int
      Data:
        type: array
        items:
          $ref: "#/definitions/BlockInfoVo"
  BlockInfoVo:
    type: object
    required:
      - height
      - hash
      - time
      - num_txs
      - validators
      - last_commit
      - total_txs
      - last_block_hash
    properties:
      height:
        type: integer
        format: int64
      hash:
        type: string
      time:
        type: string
      num_txs:
        type: integer
        format: int64
      validators:
        $ref: "#/definitions/ValInfo"
      last_commit:
        type: array
        items:
          type: string
      total_txs:
        type: integer
        format: int64
      last_block_hash:
        type: string
  ValInfo:
    type: object
    required:
      - address
      - voting_power
    properties:
      address:
        type: string
      voting_power:
        type: integer
        format: int64
  Block:
    type: object
    properties:
      block_info:
        $ref: "#/definitions/BlockInfo"
      validator_set:
        $ref: "#/definitions/ValidatorSet"
      token_flows:
        $ref: "#/definitions/TokenFlows"
      proposals:
        type: array
        items:
          $ref: "#/definitions/ProposalInfoVo"
  BlockInfo:
    type: object
    properties:
      block_height:
        type: string
      timestamp:
        type: string
      block_hash:
        type: string
      transactions:
        type: string
      propopser:
        type: string
      reward:
        $ref: "#/definitions/Coins"
      last_block:
        type: integer
        format: int64
      last_block_hash:
        type: string
      precommit_validators:
        type: string
      voting_power:
        type: string
      latest_height:
        type: string
  ProposalInfoVo:
     type: object
     required:
       - proposal
       - votes
       - result
     properties:
       proposal:
         $ref: "#/definitions/GovProposal"
       votes:
         type: array
         items:
          $ref: "#/definitions/Vote"
       result:
          $ref: "#/definitions/VoteResult"
  GovProposals:
    type: object
    required:
      - Count
      - Data
    properties:
      Count:
       type: integer
       format: int
      Data:
        type: array
        items:
          $ref: "#/definitions/GovProposal"
  GovProposal:
    type: object
    required:
      - title
      - proposal_id
      - type
      - status
      - proposer
      - submit_time
      - description
      - deposit_end_time
      - voting_end_time
      - tx_hash
      - total_deposit
      - voting_start_time
    properties:
      title:
        type: string
      proposal_id:
        type: integer
        format: uint64
      type:
        type: string
      status:
        type: string
      proposer:
        type: string
      submit_time:
        type: string
      description:
        type: string
      deposit_end_time:
        type: string
      voting_end_time:
        type: string
      tx_hash:
        type: string
      parameters:
        type: array
        items:
          $ref: "#/definitions/Param"
      voting_start_time:
        type: string
      total_deposit:
        $ref: "#/definitions/Coins"
      version:
        type: integer
        format: uint64
      software:
        type: string
      switch_height:
        type: integer
        format: uint64
      threshold:
        type: string
  Param:
    type: object
    properties:
      subspace:
        type: string
      key:
        type: string
      value:
        type: string
  Vote:
    type: object
    required:
      - voter
      - option
      - time
    properties:
      voter:
        type: string
      option:
        type: string
      time:
        type: string
  VoteResult:
     type: object
     required:
       - Yes
       - No
       - NoWithVeto
       - Abstain
     properties:
       Yes:
         type: integer
         format: int
       No:
         type: integer
         format: int
       NoWithVeto:
         type: integer
         format: int
       Abstain:
         type: integer
         fromat: int

  TokenFlow:
    type: object
    properties:
      block_height:
        type: integer
        format: int64
      block_hash:
        type: string
      tx_hash:
        type: string
      from:
        type: string
      to:
        type: string
      tx_initiator:
        type: string
      tx_type:
        type: string
      flow_type:
        type: string
      status:
        type: string
      timestamp:
        type: string
      amount:
        $ref: "#/definitions/Coin"
      fee:
        $ref: "#/definitions/Fee"
  TokenFlows:
    type: object
    properties:
      total:
        type: integer
        format: int64
      items:
        type: array
        items:
          $ref: "#/definitions/TokenFlow"
    example:
      total: 4
      items:
        [
          {
            "block_height": 1468,
            "block_hash": "88AFE4D3DDC828BA58DFF1125B9BC87140CEB06DD4C756C464D06FC944E55235",
            "tx_hash": "A462379AD307B12E9909CBCB832E6B9DFF1A6628BD6BAD73194A47C52081E6BD",
            "from": "fva1xtstdchjyzkddaptgyug62g23cta7eyzq49svq",
            "to": "faa1xtstdchjyzkddaptgyug62g23cta7eyz4y0l38",
            "amount": { "denom": "iris-atto", "amount": 319449898495734250000 },
            "fee":
              {
                "amount":
                  [{ "denom": "iris-atto", "amount": 400000000000000000 }],
                "gas": 50000,
              },
            "tx_initiator": "faa1ljemm0yznz58qxxs8xyak7fashcfxf5lssn6jm",
            "tx_type": "Delegate",
            "flow_type": "ValidatorReward",
            "status": "success",
            "timestamp": "2019-04-23T14:26:52.226+08:00",
          },
          {
            "block_height": 1468,
            "block_hash": "88AFE4D3DDC828BA58DFF1125B9BC87140CEB06DD4C756C464D06FC944E55235",
            "tx_hash": "A462379AD307B12E9909CBCB832E6B9DFF1A6628BD6BAD73194A47C52081E6BD",
            "from": "faa1ljemm0yznz58qxxs8xyak7fashcfxf5lssn6jm",
            "to": "fva1xtstdchjyzkddaptgyug62g23cta7eyzq49svq",
            "amount": { "denom": "iris-atto", "amount": 21000000000000000000 },
            "fee":
              {
                "amount":
                  [{ "denom": "iris-atto", "amount": 400000000000000000 }],
                "gas": 50000,
              },
            "tx_initiator": "faa1ljemm0yznz58qxxs8xyak7fashcfxf5lssn6jm",
            "tx_type": "Delegate",
            "flow_type": "Delegation",
            "status": "success",
            "timestamp": "2019-04-23T14:26:52.226+08:00",
          },
        ]
  Fee:
    type: object
    properties:
      amount:
        $ref: "#/definitions/Coins"
      gas:
        type: integer
        format: int64
  Coins:
    type: array
    items:
      $ref: "#/definitions/Coin"
  Coin:
    type: object
    properties:
      denom:
        type: string
      amount:
        type: integer
        format: float64
  ValidatorSet:
    type: object
    properties:
      total:
        type: integer
      items:
        type: array
        items:
          $ref: "#/definitions/Validator"
    example:
      total: 4
      items:
        [
          {
            "moniker": "irishub-node-2",
            "operator_address": "fva1xtstdchjyzkddaptgyug62g23cta7eyzq49svq",
            "consensus": "fcp1zcjduepqevwqk73gun8pp59wz6raddnsg2fczvs237cefl9ve7f94feh6lzsdr4qrf",
            "proposer_priority": "-100",
            "voting_power": "100",
          },
          {
            "moniker": "irishub-node-1",
            "operator_address": "fva1x292qss22x4rls6ygr7hhnp0et94vwwrdxhezx",
            "consensus": "fcp1zcjduepqcjgmderfahnlyrse563r2hcc3d4vjpafw03axzn3e87kfuqznjcsur8xrq",
            "proposer_priority": "-100",
            "voting_power": "100",
          },
          {
            "moniker": "irishub-node-3",
            "operator_address": "fva1amca8h9msuee5j8pg54q3sc9n9p2ss060wvhd5",
            "consensus": "fcp1zcjduepq3hy0q3ltgktya5gzvjfmkrhkeqzqau9t927ne8wdts36en490q7s8lxjq2",
            "proposer_priority": "-100",
            "voting_power": "100",
          },
          {
            "moniker": "irishub-node-0",
            "operator_address": "fva1d7rxfhyhqzgudv5nmne548t3xrk4tvazpg94cu",
            "consensus": "fcp1zcjduepqujegylnmyuymekm7sk70g5up0xq6p5r8zaj5rpjey7tqxxp0z3zqjns5cy",
            "proposer_priority": "300",
            "voting_power": "100",
          },
        ]
  Validator:
    type: object
    properties:
      moniker:
        type: string
      operator_address:
        type: string
      consensus:
        type: string
      proposer_priority:
        type: string
      voting_power:
        type: string
  error:
    type: object
    properties:
      code:
        type: string
      msg:
        type: string
