// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-10-14 12:14:53.447359 +0800 CST m=+0.114232922

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/api/account/{address}": {
            "get": {
                "description": "get detail of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountVo"
                        }
                    }
                }
            }
        },
        "/api/account/{address}/delegations": {
            "get": {
                "description": "get delegations of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountDelegationsRespond"
                        }
                    }
                }
            }
        },
        "/api/account/{address}/rewards": {
            "get": {
                "description": "get rewards of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountRewardsVo"
                        }
                    }
                }
            }
        },
        "/api/account/{address}/unbonding_delegations": {
            "get": {
                "description": "get unbondingdelegations of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountUnbondingDelegationsRespond"
                        }
                    }
                }
            }
        },
        "/api/accounts": {
            "get": {
                "description": "get list of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountsInfoRespond"
                        }
                    }
                }
            }
        },
        "/api/asset/gateways/{moniker}": {
            "get": {
                "description": "get gateway assets token detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "moniker",
                        "name": "moniker",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetGateways"
                        }
                    }
                }
            }
        },
        "/api/asset/tokens": {
            "get": {
                "description": "get asset tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "source",
                        "name": "source",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetTokensRespond"
                        }
                    }
                }
            }
        },
        "/api/asset/tokens/{token_id}": {
            "get": {
                "description": "get assets token detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token_id",
                        "name": "token_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetTokens"
                        }
                    }
                }
            }
        },
        "/api/assets/gateway/txs": {
            "get": {
                "description": "get assets txs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "gateway",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page num",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "txs type",
                        "name": "tx_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asset symbol",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gateway",
                        "name": "gateway",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "moniker",
                        "name": "moniker",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "if used count",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetsRespond"
                        }
                    }
                }
            }
        },
        "/api/assets/native/txs": {
            "get": {
                "description": "get assets txs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "native",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page num",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "txs type",
                        "name": "tx_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asset symbol",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "if used count",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetsRespond"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.Coin": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "utils.CoinAsStr": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "utils.Coins": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "number"
                    },
                    "denom": {
                        "type": "string"
                    }
                }
            }
        },
        "utils.CoinsAsStr": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "string"
                    },
                    "denom": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AccountDelegationsRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "object",
                        "$ref": "#/definitions/utils.Coin"
                    },
                    "height": {
                        "type": "string"
                    },
                    "moniker": {
                        "type": "string"
                    },
                    "shares": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AccountDelegationsVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "height": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "shares": {
                    "type": "string"
                }
            }
        },
        "vo.AccountInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.Coin"
                    }
                },
                "percent": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "update_at": {
                    "type": "integer"
                }
            }
        },
        "vo.AccountRewardsVo": {
            "type": "object",
            "properties": {
                "commission_rewards": {
                    "type": "object",
                    "$ref": "#/definitions/utils.CoinsAsStr"
                },
                "delagations_rewards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.DelagationsRewards"
                    }
                },
                "total_rewards": {
                    "type": "object",
                    "$ref": "#/definitions/utils.CoinsAsStr"
                }
            }
        },
        "vo.AccountUnbondingDelegationsRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "object",
                        "$ref": "#/definitions/utils.Coin"
                    },
                    "end_time": {
                        "type": "string"
                    },
                    "height": {
                        "type": "string"
                    },
                    "moniker": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AccountUnbondingDelegationsVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "end_time": {
                    "type": "string"
                },
                "height": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                }
            }
        },
        "vo.AccountVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coins"
                },
                "deposits": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "isProfiler": {
                    "type": "boolean"
                },
                "moniker": {
                    "type": "string"
                },
                "operator_address": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "withdrawAddress": {
                    "type": "string"
                }
            }
        },
        "vo.AccountsInfoRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "balance": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/utils.Coin"
                        }
                    },
                    "percent": {
                        "type": "number"
                    },
                    "rank": {
                        "type": "integer"
                    },
                    "update_at": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.ActualFee": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "vo.AssetGateways": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "icons": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "vo.AssetTokens": {
            "type": "object",
            "properties": {
                "asset_gateway": {
                    "type": "object",
                    "$ref": "#/definitions/vo.AssetGateways"
                },
                "canonical_symbol": {
                    "type": "string"
                },
                "decimal": {
                    "type": "integer"
                },
                "family": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "initial_supply": {
                    "type": "string"
                },
                "max_supply": {
                    "type": "string"
                },
                "min_unit_alias": {
                    "type": "string"
                },
                "mintable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "total_supply": {
                    "type": "string"
                }
            }
        },
        "vo.AssetTokensRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "asset_gateway": {
                        "type": "object",
                        "$ref": "#/definitions/vo.AssetGateways"
                    },
                    "canonical_symbol": {
                        "type": "string"
                    },
                    "decimal": {
                        "type": "integer"
                    },
                    "family": {
                        "type": "string"
                    },
                    "gateway": {
                        "type": "string"
                    },
                    "initial_supply": {
                        "type": "string"
                    },
                    "max_supply": {
                        "type": "string"
                    },
                    "min_unit_alias": {
                        "type": "string"
                    },
                    "mintable": {
                        "type": "boolean"
                    },
                    "name": {
                        "type": "string"
                    },
                    "owner": {
                        "type": "string"
                    },
                    "source": {
                        "type": "string"
                    },
                    "symbol": {
                        "type": "string"
                    },
                    "token_id": {
                        "type": "string"
                    },
                    "total_supply": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AssetsRespond": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "txs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.AssetsVo"
                    }
                }
            }
        },
        "vo.AssetsVo": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "canonical_symbol": {
                    "type": "string"
                },
                "decimal": {
                    "type": "integer"
                },
                "dst_owner": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "initial_supply": {
                    "type": "integer"
                },
                "max_supply": {
                    "type": "integer"
                },
                "mint_to": {
                    "type": "string"
                },
                "mintable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "src_owner": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "symbol_min": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "tx_fee": {
                    "type": "object",
                    "$ref": "#/definitions/vo.ActualFee"
                },
                "tx_hash": {
                    "type": "string"
                },
                "tx_status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "vo.DelagationsRewards": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.CoinsAsStr"
                },
                "moniker": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
