// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-10-14 13:44:42.568907 +0800 CST m=+0.116117322

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/api/account/{address}": {
            "get": {
                "description": "get detail of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountVo"
                        }
                    }
                }
            }
        },
        "/api/account/{address}/delegations": {
            "get": {
                "description": "get delegations of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountDelegationsRespond"
                        }
                    }
                }
            }
        },
        "/api/account/{address}/rewards": {
            "get": {
                "description": "get rewards of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountRewardsVo"
                        }
                    }
                }
            }
        },
        "/api/account/{address}/unbonding_delegations": {
            "get": {
                "description": "get unbondingdelegations of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "account address",
                        "name": "address",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountUnbondingDelegationsRespond"
                        }
                    }
                }
            }
        },
        "/api/accounts": {
            "get": {
                "description": "get list of account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "list",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AccountsInfoRespond"
                        }
                    }
                }
            }
        },
        "/api/asset/gateways/{moniker}": {
            "get": {
                "description": "get gateway assets token detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "moniker",
                        "name": "moniker",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetGateways"
                        }
                    }
                }
            }
        },
        "/api/asset/tokens": {
            "get": {
                "description": "get asset tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "source",
                        "name": "source",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetTokensRespond"
                        }
                    }
                }
            }
        },
        "/api/asset/tokens/{token_id}": {
            "get": {
                "description": "get assets token detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token_id",
                        "name": "token_id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetTokens"
                        }
                    }
                }
            }
        },
        "/api/assets/gateway/txs": {
            "get": {
                "description": "get assets txs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "gateway",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page num",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "txs type",
                        "name": "tx_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asset symbol",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "gateway",
                        "name": "gateway",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "moniker",
                        "name": "moniker",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "if used count",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetsRespond"
                        }
                    }
                }
            }
        },
        "/api/assets/native/txs": {
            "get": {
                "description": "get assets txs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "native",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page num",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "txs type",
                        "name": "tx_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asset symbol",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "if used count",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.AssetsRespond"
                        }
                    }
                }
            }
        },
        "/api/block/blockinfo/{height}": {
            "get": {
                "description": "get block info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "block"
                ],
                "summary": "detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.BlockInfo"
                        }
                    }
                }
            }
        },
        "/api/block/latestheight": {
            "get": {
                "description": "get block latestheight",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "block"
                ],
                "summary": "latest",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/int64"
                        }
                    }
                }
            }
        },
        "/api/block/validatorset/{height}": {
            "get": {
                "description": "get  block validatorset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "block"
                ],
                "summary": "block validatorset",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page num",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.ValidatorSet"
                        }
                    }
                }
            }
        },
        "/api/blocks": {
            "get": {
                "description": "get blocks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "block"
                ],
                "summary": "list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page num",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.BlockForListRespond"
                        }
                    }
                }
            }
        },
        "/api/blocks/recent": {
            "get": {
                "description": "get recent blocks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "block"
                ],
                "summary": "blocks recent",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/vo.BlockInfoVoRespond"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.Coin": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "utils.CoinAsStr": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "utils.Coins": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "number"
                    },
                    "denom": {
                        "type": "string"
                    }
                }
            }
        },
        "utils.CoinsAsStr": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "amount": {
                        "type": "string"
                    },
                    "denom": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AccountDelegationsRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "object",
                        "$ref": "#/definitions/utils.Coin"
                    },
                    "height": {
                        "type": "string"
                    },
                    "moniker": {
                        "type": "string"
                    },
                    "shares": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AccountDelegationsVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "height": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "shares": {
                    "type": "string"
                }
            }
        },
        "vo.AccountInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/utils.Coin"
                    }
                },
                "percent": {
                    "type": "number"
                },
                "rank": {
                    "type": "integer"
                },
                "update_at": {
                    "type": "integer"
                }
            }
        },
        "vo.AccountRewardsVo": {
            "type": "object",
            "properties": {
                "commission_rewards": {
                    "type": "object",
                    "$ref": "#/definitions/utils.CoinsAsStr"
                },
                "delagations_rewards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.DelagationsRewards"
                    }
                },
                "total_rewards": {
                    "type": "object",
                    "$ref": "#/definitions/utils.CoinsAsStr"
                }
            }
        },
        "vo.AccountUnbondingDelegationsRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "object",
                        "$ref": "#/definitions/utils.Coin"
                    },
                    "end_time": {
                        "type": "string"
                    },
                    "height": {
                        "type": "string"
                    },
                    "moniker": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AccountUnbondingDelegationsVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "end_time": {
                    "type": "string"
                },
                "height": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                }
            }
        },
        "vo.AccountVo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coins"
                },
                "deposits": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "isProfiler": {
                    "type": "boolean"
                },
                "moniker": {
                    "type": "string"
                },
                "operator_address": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "withdrawAddress": {
                    "type": "string"
                }
            }
        },
        "vo.AccountsInfoRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "balance": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/utils.Coin"
                        }
                    },
                    "percent": {
                        "type": "number"
                    },
                    "rank": {
                        "type": "integer"
                    },
                    "update_at": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.ActualFee": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "denom": {
                    "type": "string"
                }
            }
        },
        "vo.AssetGateways": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "icons": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "vo.AssetTokens": {
            "type": "object",
            "properties": {
                "asset_gateway": {
                    "type": "object",
                    "$ref": "#/definitions/vo.AssetGateways"
                },
                "canonical_symbol": {
                    "type": "string"
                },
                "decimal": {
                    "type": "integer"
                },
                "family": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "initial_supply": {
                    "type": "string"
                },
                "max_supply": {
                    "type": "string"
                },
                "min_unit_alias": {
                    "type": "string"
                },
                "mintable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "total_supply": {
                    "type": "string"
                }
            }
        },
        "vo.AssetTokensRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "asset_gateway": {
                        "type": "object",
                        "$ref": "#/definitions/vo.AssetGateways"
                    },
                    "canonical_symbol": {
                        "type": "string"
                    },
                    "decimal": {
                        "type": "integer"
                    },
                    "family": {
                        "type": "string"
                    },
                    "gateway": {
                        "type": "string"
                    },
                    "initial_supply": {
                        "type": "string"
                    },
                    "max_supply": {
                        "type": "string"
                    },
                    "min_unit_alias": {
                        "type": "string"
                    },
                    "mintable": {
                        "type": "boolean"
                    },
                    "name": {
                        "type": "string"
                    },
                    "owner": {
                        "type": "string"
                    },
                    "source": {
                        "type": "string"
                    },
                    "symbol": {
                        "type": "string"
                    },
                    "token_id": {
                        "type": "string"
                    },
                    "total_supply": {
                        "type": "string"
                    }
                }
            }
        },
        "vo.AssetsRespond": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "txs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.AssetsVo"
                    }
                }
            }
        },
        "vo.AssetsVo": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "canonical_symbol": {
                    "type": "string"
                },
                "decimal": {
                    "type": "integer"
                },
                "dst_owner": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "initial_supply": {
                    "type": "integer"
                },
                "max_supply": {
                    "type": "integer"
                },
                "mint_to": {
                    "type": "string"
                },
                "mintable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "src_owner": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "symbol_min": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "tx_fee": {
                    "type": "object",
                    "$ref": "#/definitions/vo.ActualFee"
                },
                "tx_hash": {
                    "type": "string"
                },
                "tx_status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "vo.BlockForList": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "precommit_validator_num": {
                    "type": "integer"
                },
                "precommit_voting_power": {
                    "type": "integer"
                },
                "proposer_as_validator_addr": {
                    "type": "string"
                },
                "proposer_moniker": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "txs_num": {
                    "type": "integer"
                },
                "validator_num_for_height": {
                    "type": "integer"
                },
                "voting_power_for_height": {
                    "type": "integer"
                }
            }
        },
        "vo.BlockForListRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "height": {
                        "type": "integer"
                    },
                    "precommit_validator_num": {
                        "type": "integer"
                    },
                    "precommit_voting_power": {
                        "type": "integer"
                    },
                    "proposer_as_validator_addr": {
                        "type": "string"
                    },
                    "proposer_moniker": {
                        "type": "string"
                    },
                    "timestamp": {
                        "type": "string"
                    },
                    "txs_num": {
                        "type": "integer"
                    },
                    "validator_num_for_height": {
                        "type": "integer"
                    },
                    "voting_power_for_height": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.BlockInfo": {
            "type": "object",
            "properties": {
                "block_hash": {
                    "type": "string"
                },
                "block_height": {
                    "type": "string"
                },
                "latest_height": {
                    "type": "string"
                },
                "mint_coin": {
                    "type": "object",
                    "$ref": "#/definitions/utils.Coin"
                },
                "precommit_validator_num": {
                    "type": "object"
                },
                "precommit_voting_power": {
                    "type": "object"
                },
                "propopser_addr": {
                    "type": "string"
                },
                "propopser_moniker": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "total_validator_num": {
                    "type": "integer"
                },
                "total_voting_power": {
                    "type": "integer"
                },
                "transactions": {
                    "type": "string"
                }
            }
        },
        "vo.BlockInfoVo": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "last_block_hash": {
                    "type": "string"
                },
                "last_commit": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "num_txs": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "total_txs": {
                    "type": "integer"
                },
                "validators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.ValInfo"
                    }
                }
            }
        },
        "vo.BlockInfoVoRespond": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "hash": {
                        "type": "string"
                    },
                    "height": {
                        "type": "integer"
                    },
                    "last_block_hash": {
                        "type": "string"
                    },
                    "last_commit": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "num_txs": {
                        "type": "integer"
                    },
                    "time": {
                        "type": "string"
                    },
                    "total_txs": {
                        "type": "integer"
                    },
                    "validators": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/vo.ValInfo"
                        }
                    }
                }
            }
        },
        "vo.BlockValidator": {
            "type": "object",
            "properties": {
                "consensus": {
                    "type": "string"
                },
                "is_proposer": {
                    "type": "boolean"
                },
                "moniker": {
                    "type": "string"
                },
                "operator_address": {
                    "type": "string"
                },
                "proposer_priority": {
                    "type": "string"
                },
                "voting_power": {
                    "type": "string"
                }
            }
        },
        "vo.DelagationsRewards": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "amount": {
                    "type": "object",
                    "$ref": "#/definitions/utils.CoinsAsStr"
                },
                "moniker": {
                    "type": "string"
                }
            }
        },
        "vo.ValInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "voting_power": {
                    "type": "integer"
                }
            }
        },
        "vo.ValidatorSet": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.BlockValidator"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
