
const {
    VUE_APP_NATIVE_TOKEN_DENOM,
    VUE_APP_DISPLAY_TOKEN,
    VUE_APP_NORMAL_2_ATTO_DECIMAL,
} = process.env;

export const NATIVE_TOKEN = VUE_APP_NATIVE_TOKEN_DENOM;
export const DISPLAY_TOKEN = VUE_APP_DISPLAY_TOKEN;
export const NORMAL_2_ATTO_DECIMAL = VUE_APP_NORMAL_2_ATTO_DECIMAL;